### ISSUE TITLE
TO-DO tasks

### ISSUE THREAD

**Issue by gabru-md** [gabru-md/susi-terminal#1]
- [X]  Add `answer` type Responses
 - [X]  Add `Table` type Responses
 - [x] Add `map` type Responses i.e. a valid alternative to `map`
 - [x] Update `README.md`
 - [ ] Add Gif to readme
 - [ ] Add `Travis`
 - [ ] Add `Eslint`
 - [x] Add song playback option
 - [x] Display description of `susi ai` when user types `susi` in the terminal
 - [ ] Add more here to make it a complete Personal Assistant
